### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by NickBarty**
- Check formatting
- Check variable names
- Check logic
@BelleMardy

### CODE REVIEW

**Comment by NickBarty** [comment]
@BelleMardy

**Comment by BelleMardy** [comment]
Nick, I can write another comment

**Comment by BelleMardy** [comment]
Nothing to say, good coding

**Comment by NickBarty** [comment]
@JcobMadeley hi

**Comment by NickBarty** [comment]
@jacobmadeley hi

**Pull request merged**
